INSERT INTO Preguntas VALUES (1,'¿Disfruta su hijo cuando se balancea o se le hace saltar sobre sus rodillas?',0)
INSERT INTO Preguntas VALUES (1,'¿Muestra interes por otros niños?',0)
INSERT INTO Preguntas VALUES (1,'¿Le gusta subirse a las cosas como sillones, escalones, juegos del parque?',0)
INSERT INTO Preguntas VALUES (1,'¿Le gusta que el adulto juegue con el o ella "cucu-tras"(taparce los ojos y luego descubrirlos;jugar a esconderce y aparecer de repente?',0)
INSERT INTO Preguntas VALUES (1,'¿Hace juegos imaginativos. como si hablara por telefono,como si estuviera dando de comer a una miñeca o si estuviera conduciendo un coche?',0)
INSERT INTO Preguntas VALUES (1,'¿Suele señalar con el dedo para pedir algo?',0)
INSERT INTO Preguntas VALUES (1,'¿suele señañar con el dedo para indicar que algo le llama la atencion?',0)
INSERT INTO Preguntas VALUES (1,'¿Puede juegar adecuadamente con piezas y juguetes pequeños,sin unicamente chuparlos?',0)
INSERT INTO Preguntas VALUES (1,'¿suele traer objetos para mostracelos?',0)
INSERT INTO Preguntas VALUES (1,'¿suele mirarle a los ojos durante unos segundos?',0)
INSERT INTO Preguntas VALUES (1,'¿Le parece demaciado senciable a ruidos poco intensos?',1)
INSERT INTO Preguntas VALUES (1,'¿sonrie al verle a usted o cuando usted le sonrie?',0)
INSERT INTO Preguntas VALUES (1,'¿puede imitar o repetir gestos o acciones que usted hace?',0)
INSERT INTO Preguntas VALUES (1,'¿responde al llamarlo por su nombre?',0)
INSERT INTO Preguntas VALUES (1,'si usted señala con el dedo un juguete al otro lado de la habitacion,¿dirije su atencion  hacie el juguete?',0)
INSERT INTO Preguntas VALUES (1,'¿Ha aprendido ya a caminar?',0)
INSERT INTO Preguntas VALUES (1,'si ustede esta mirando algo atentamente,¿su hijo o hija se pone tambien a mirarlo?',0)
INSERT INTO Preguntas VALUES (1,'¿hace su hijo movimientos raros con los dedos, por ejemplo, acercarselos a los ojos?',1)
INSERT INTO Preguntas VALUES (1,'¿Intenta que usted preste atencion a las actividades que el o ella esta haciendo?',0)
INSERT INTO Preguntas VALUES (1,'¿Alguna vez ha pensado que su hijo o hija podria tener sordera?',1)
INSERT INTO Preguntas VALUES (1,'¿Entiende su hijo o hija lo que la gente dice?',0)
INSERT INTO Preguntas VALUES (1,'¿se queda a beces mirando al vacio o va de un lado al otro sin propocito?',1)
INSERT INTO Preguntas VALUES (1,'si su hijo se tiene que enfrentarse a una situcion desconocida,¿le mira a usted primero a la cara para saber como reaccionar?',0)
